# paper: 
# 	latex paper
# 	bibtex paper 
# 	latex paper 
# 	latex paper 
# 	latex paper
# 	dvipdf paper

paper_g: 
	pdflatex paper_g
	bibtex paper_g 
	pdflatex paper_g 
	pdflatex paper_g 
	pdflatex paper_g

clean:
	rm -f *.aux *.log *.dvi *.blg *.out *~


